config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'

  get 'movies/show'

  resource :session, :only => [:new, :create, :destroy]
  get "login" => "sessions#new"
  delete "logout" => "sessions#destroy"
  get 'logout' => "sessions#destroy"

  resources :users
  resources :movies

  root "users#new"

  get '*path' => redirect("/")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/soda.rb
require 'soda/client'


class Soda
  attr_reader :client, :mechanize

  def initialize
    @client = SODA::Client.new({:domain => "data.sfgov.org", :app_token => "oxIaSRfUvc6ioOslIXneYkiVx"})
    Tmdb::Api.key("066f3cdd124c632840cc0694e49d3662")
    @mechanize = Mechanize.new
  end

  def movies_with_address(address)
    return "Nothing there" if address == nil
    client.get("wwmu-gmzc", {
      "$where" => "lower(locations) like '%#{address.downcase}%'"
      })
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :password, 
            :length => { :in => 5..20 }, 
            :allow_nil => true 
  validates :first_name, :last_name, :email, :street, :number_street, presence: true
  validates :email, uniqueness: true

  reverse_geocoded_by :latitude, :longitude
  geocoded_by :full_street_address
  after_validation :geocode
          

  def generate_token
    begin
      self[:auth_token] = SecureRandom.urlsafe_base64
    end while User.exists?(:auth_token => self[:auth_token])
  end

  def regenerate_auth_token
    self.auth_token = nil
    generate_token
    save!
  end

  def self.suffixes
    return [["Avenue", "Avenue"],["Drive", "Drive"],["Street", "Street"],["Place", "Place"],["Court", "Court"],["Boulevard", "Boulevard"]]
  end

  def name
    self.first_name + " " + self.last_name
  end

  def full_street_address
    self.number_street.to_s + " " + self.street + " " + "San Francisco"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def check_params(street) 
    "ONEWORD " + street if street.length < 2
    street if street.length > 1
  end
  
  def set_user
    @user = User.find_by_id(params[:user_id])
    redirect_to root_path, :flash=> {:danger => "Unable to find that user"} unless @user
  end

  def sign_in(user)
    user.regenerate_auth_token
    cookies[:auth_token] = user.auth_token
    @current_user = user
  end

  def permanent_sign_in(user)
    user.regenerate_auth_token
    cookies.permanent[:auth_token] = user.auth_token
    @current_user = user
  end

  def sign_out
    @current_user = nil
    cookies.delete(:auth_token)
  end

  def current_user
    @current_user ||= User.find_by_auth_token(cookies[:auth_token]) if cookies[:auth_token]
  end

  helper_method :current_user

  def signed_in_user?
    !!current_user
  end

  helper_method :signed_in_user?

  def require_login
    unless signed_in_user?
      flash[:danger] = "You are not logged in. Please login."
      redirect_to new_user_path
    end
  end

  def require_current_user
    unless current_user
      flash[:danger] = "You're not allowed there. Nice try."
      redirect_to "http://nouveller.com/404/"
    end
  end 

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  helper UsersHelper

  def index
    @client = Soda.new
    @street = check_params(params[:search])
    @results = @client.movies_with_address(@street.split(" ")[1])
  end

  def show
    @title = params[:title]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      if params[:remember_me]
        permanent_sign_in(@user)
      else
        sign_in(@user)
      end
        flash[:success] = "You've successfully signed into SF Locater!"
        redirect_to user_path(current_user)
    else
      flash[:danger] = "We did not sign you. Please provide a valid email and password"
      redirect_to root_url
    end
  end

  def destroy
    sign_out
    flash[:success] = "You've successfully signed out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:edit, :show, :update]
  helper UsersHelper
  
  def new
    @user = User.new
    @suffixes = User.suffixes
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def show
    @user = User.find_by_id(params[:id])
    @client = Soda.new
    @results = @client.movies_with_address(@user.street)
  end

  def index
  end

  def update
    if current_user.update(user_params) 
      flash[:success] = "Your stuff has been updated!"
      redirect_to current_user 
    else
      flash[:danger] = "Failed to update your stuff" 
      current_user.errors.full_messages.join(", ")
      redirect_to current_user
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome!"
      redirect_to @user
    else
      flash.now[:danger] = "Please fill out all fields and make sure your password and password confirmation match"
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :number_street, :street, :street_suffix, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def get_movie(movie)
    Tmdb::Movie
    .find(movie)
    .first 
  end

  def movie_poster(movie)
    get_movie(movie).poster_path
  end

  def movie_link(movie)
    "http://www.imdb.com/title/tt#{get_movie(movie)}" if get_movie(movie)
  end

  def tagline_movie(movie)
    get_movie(movie).tagline if get_movie(movie)
  end

  def average_movie(movie)
    get_movie(movie).average if get_movie(movie)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sanfranmovies</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Baloo+Tamma">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= render "shared/log_out" %></br></br>
    <%= render "shared/search" %>


    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1 class="text-center">Movies Search</h1>

<h3 class="text-center">Movies Filmed Near: <span class="street-address"><%= @street %></span></h3>
<% if @results == "Nothing there" || @results.empty? %>
  <h1 class="text-center">Nothing is at '<%=@street%>'... :(</h1></br><br>
<% else %>
  <% @results.each do |movie| %>
    <div class="col-md-4 movie-show text-center">
      <%= movie.title %></br>
      <%= link_to "Click Here for more information", movie_path(movie.title) %>
      <%= image_tag("http://image.tmdb.org/t/p/original#{movie_poster(movie.title)}", class: "movie-poster-show")%></br>   
    </div>
  <% end %>
<% end %>

app/views/movies/show.html.erb
<div class="text-center">
   <h2>Title: <%= @title %></br></h2>
   <h2>IMBD vote average: <%= get_movie(@title).vote_average %></h2>
   <h3>Tagline: <%= get_movie(@title).tagline %></h3>
   <h4>Overview: <%= get_movie(@title).overview %></h4>
   <h2>Budget:</h2> <p><%= get_movie(@title).budget %></p>
</div>

app/views/shared/_flash.html.erb
 <div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/shared/_log_out.html.erb
<% if signed_in_user? %>
  <div class="log-in-information">
    <div class= "col-xs-9 col-md-9 logged-in-text">
      Welcome, <%= link_to current_user.email, user_path(current_user)  %>
      <%= link_to "Logout", logout_path, :method => :delete %>
    </div>
  </div>
<% else %>
  <%= form_tag session_path do  %>
    <div class="log-in-information">
      <div class="col-xs-3 col-md-3">
        <%= text_field_tag :email, nil, placeholder: "Email", html: {class: "form-control"} %>
      </div>
      <div class="col-xs-3 col-md-3">
        <%= password_field_tag :password, nil, placeholder: "Password", html: {class: "form-control"} %>
      </div>

      <div class="col-xs-2 col-md-2">
        <%= label_tag "Remember me?", nil, {class: "danebook-text remember-me"} %>
        <%= check_box_tag :remember_me %>
      </div>
      <div class="col-xs-1 col-md-1">
        <%= submit_tag "Log in", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
<% end %></br></br>

app/views/shared/_search.html.erb
<div class="text-center">
  <h5 class="text-center">Want to see if a movie was filmed where you are now? Input your current address below</h5>
  <%= form_tag("/movies", method: "get") do %>
    <%= text_field_tag(:search, params[:search], placeholder: "Example: '123 Main Street'", class: "search-input") %>
    <%= submit_tag("Search", name: nil, class: "btn btn-primary") %>
  <% end %>
</div></br></br>

app/views/users/edit.html.erb
<h1 class= "text-center"> Edit your information here</h1>
<div class= "container">
  <%= form_for @user, class: "form-group" do |f| %>
    <div class= "col-md-12 sign-up-field">
      <%= f.label "First Name" %>
      <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %></br>
    </div>
    <div class=" col-md-12 sign-up-field">
      <%= f.label "Last Name" %>
      <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %></br>
    </div>
    <div class=" col-md-12 sign-up-field">
      <%= f.label "Street Number" %>
      <%= f.number_field :number_street, placeholder: "Street number", class: "form-control" %></br>
    </div>
    <div class=" col-md-12 sign-up-field">
      <%= f.label "Street Number" %>
      <%= f.text_field :street, placeholder: "Street name", class: "form-control" %></br>
    </div>
    <div class=" col-md-12 sign-up-field">
      <%= f.label "Street Suffix(Ave, Street, etc)" %>
      <%= f.text_field :street_suffix, placeholder: "Street Suffix", class: "form-control" %></br>
    </div>
    <div class= "col-md-12 sign-up-field">
      <%= f.label "Email" %>
        <%= f.text_field :email, placeholder: "Email", class: "form-control" %></br>
    </div>
    <div class="col-md-6">
      <%= f.submit "Update!", class: "btn btn-success sign-up-field text-center" %></br>
    </div>
  <% end %>
</div></br></br>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <h1 class="website-title text-center">San Fransico Movie Locater </h1>
  <%= image_tag("http://www.sanfrancisco.travel/sites/sftraveldev.prod.acquia-sites.com/files/field/image/site-photo.jpg", class: "san-francisco-image" )%>
  <% unless signed_in_user? %>
    <%= form_for @user, class: "form-group" do |f| %>
      <div class= "col-md-12 sign-up-field">
        <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
      </div>
      <div class=" col-md-12 sign-up-field">
        <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>
      <div class=" col-md-12 sign-up-field">
        <%= f.number_field :number_street, placeholder: "Street number", class: "form-control" %>
      </div>
      <div class=" col-md-12 sign-up-field">
        <%= f.text_field :street, placeholder: "Street name", class: "form-control" %>
      </div>
      <div class=" col-md-12 sign-up-field">
        <%= f.text_field :street_suffix, placeholder: "Street Suffix", class: "form-control" %>
      </div>
      <div class= "col-md-12 sign-up-field">
          <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
      </div>
      <div class= "col-md-6 sign-up-field">
        <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
      </div>
      <div class= "col-md-6 sign-up-field">
        <%= f.password_field :password_confirmation, placeholder: "Password Confirmation", class: "form-control" %>
      </div>
      <div class="col-md-6">
        <%= f.submit "Sign Up!", class: "btn btn-success sign-up-field text-center" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container text-center">
  <h3 class="text-center">Your Information</h3>
  Latitude: <%= @user.latitude  if current_user == @user %></br>
  longitude: <%= @user.longitude  if current_user == @user %></br>
  Name: <%= @user.name %></br>
  Email: <%= @user.email if current_user == @user %></br>
  Address: <%= @user.number_street if current_user == @user %>
  <%= @user.street if current_user == @user %>
  <%= @user.street_suffix if current_user == @user %></br>
  <%= link_to "Edit your information", edit_user_path(current_user) %>
</div></br></br></br>

<h3 class="text-center">Movies Near Your address</h3>
<% if @results == "Nothing there" %>
  <h1 class="text-center">Nothing is at your address... :(</h1></br><br>
<% else %>
  <% @results.each do |movie| %>
    <div class="col-md-4 movie-show text-center">
      <%= link_to "Click Here for more information", movie_path(movie) %></br>
      <%= movie.title %></br>
      <%= image_tag("http://image.tmdb.org/t/p/original#{movie_poster(movie.title)}", class: "movie-poster-show")%></br>   
    </div>
  <% end %>
<% end %>